### PR TITLE
Allow latest puppet-lint version

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Comment by ekohl** [comment]
@janlam7 I was told you may be able to help. Could you take a look at merging and releasing this? If @hostnet is no longer interested in its maintenance, @voxpupuli would be happy to take it over.

**Comment by fbs** [comment]
I'll try to poke some people as well. As the author I wouldn't mind it being transferred to voxpupuli but I have no say in it anymore ;)

**Comment by rswarts** [comment]
Hi there, we are happy to have @voxpupuli take it over. Please let me know how to get that going.

**Comment by bastelfreak** [comment]
@rswarts awesome! I sent you a GitHub invitation to join Vox Pupuli. After you accepted it, you can migrate the github repo to vox pupuli. Afterwards please agg pmc@voxpupuli.org as maintainer on rubygems. We will configure new releases on our side, that's about it. If you like, you and your coworkers are more than happy to become Vox Pupuli members, then you can keep merge access to the repo. Vox Pupuli membership doesn't come with any costs or obligations. We're also around in #voxpupuli on Libera IRC and slack at https://slack.puppet.com/ if you have any questions.

**Comment by bastelfreak** [comment]
Hi @rswarts ! Please let us know if you've any questions about the migration or if you can help somehow.

**Comment by rswarts** [comment]
Hi @bastelfreak, sorry I haven't gotten around to this yet. Invitation seems to have expired, can you please resend? I'll get on this today or tomorrow.

**Comment by bastelfreak** [comment]
Hey I just resent the invitation :)

**Comment by bastelfreak** [comment]
@rswarts thanks for migrating the repo! Please add pmc@voxpupuli.org as maintainer on rubygems. Afterwards we can do the rest on our side.

**Pull request merged**
